# Generated by Django 5.2.16 on 2026-07-27 00:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredParty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=50)),
                ('insured_id_number', models.CharField(blank=True, max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'insured parties',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='claims_insu_last_na_7a89e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='claims_pati_last_na_7b9441_idx'), models.Index(fields=['date_of_birth'], name='claims_pati_date_of_1a48f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_type', models.CharField(choices=[('medicare', 'Medicare'), ('medicaid', 'Medicaid'), ('commercial', 'Commercial'), ('other', 'Other')], default='medicare', max_length=50)),
                ('payer_identifier', models.CharField(blank=True, max_length=100)),
                ('medicare_administrative_contractor', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['payer_name'],
                'indexes': [models.Index(fields=['payer_identifier'], name='claims_paye_payer_i_7b3c3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('validation_failed', 'Validation Failed'), ('ready_for_837p', 'Ready for 837P'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('denied', 'Denied')], default='draft', max_length=50)),
                ('validation_status', models.CharField(blank=True, max_length=50)),
                ('validation_message', models.TextField(blank=True)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('total_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('insured_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='claims.insuredparty')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.patient')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.payer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('npi', models.CharField(blank=True, max_length=20)),
                ('taxonomy_code', models.CharField(blank=True, max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['organization_name', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['npi'], name='claims_prov_npi_8d42be_idx'), models.Index(fields=['taxonomy_code'], name='claims_prov_taxonom_f8276a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_role', models.CharField(choices=[('billing', 'Billing Provider'), ('rendering', 'Rendering Provider'), ('referring', 'Referring Provider'), ('facility', 'Service Facility')], max_length=50)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_providers', to='claims.claim')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_providers', to='claims.provider')),
            ],
            options={
                'ordering': ['claim', 'provider_role'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_from_date', models.DateField(blank=True, null=True)),
                ('service_to_date', models.DateField(blank=True, null=True)),
                ('place_of_service', models.CharField(blank=True, max_length=10)),
                ('procedure_code', models.CharField(max_length=20)),
                ('modifier_1', models.CharField(blank=True, max_length=10)),
                ('modifier_2', models.CharField(blank=True, max_length=10)),
                ('modifier_3', models.CharField(blank=True, max_length=10)),
                ('modifier_4', models.CharField(blank=True, max_length=10)),
                ('diagnosis_pointer_1', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnosis_pointer_2', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnosis_pointer_3', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnosis_pointer_4', models.PositiveIntegerField(blank=True, null=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('units', models.PositiveIntegerField(default=1)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='claims.claim')),
            ],
            options={
                'ordering': ['claim', 'service_from_date', 'procedure_code'],
            },
        ),
        migrations.CreateModel(
            name='ClaimAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_description', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim'], name='claims_clai_claim_i_1b31ff_idx'), models.Index(fields=['event_type'], name='claims_clai_event_t_cdc853_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClaimDiagnosis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis_code', models.CharField(max_length=20)),
                ('diagnosis_order', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='claims.claim')),
            ],
            options={
                'verbose_name_plural': 'claim diagnoses',
                'ordering': ['claim', 'diagnosis_order'],
                'indexes': [models.Index(fields=['diagnosis_code'], name='claims_clai_diagnos_45b966_idx')],
                'constraints': [models.UniqueConstraint(fields=('claim', 'diagnosis_order'), name='unique_claim_diagnosis_order')],
            },
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient'], name='claims_clai_patient_d7ddbd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['payer'], name='claims_clai_payer_i_61c515_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_start_date', 'service_end_date'], name='claims_clai_service_b08d25_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimprovider',
            constraint=models.UniqueConstraint(fields=('claim', 'provider', 'provider_role'), name='unique_claim_provider_role'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['claim'], name='claims_serv_claim_i_3fc234_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceline',
            index=models.Index(fields=['procedure_code'], name='claims_serv_procedu_72ec60_idx'),
        ),
    ]
