# Generated by Django 5.2.16 on 2026-08-03 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCoverage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_sequence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('other', 'Other')], default='primary', max_length=50)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=50)),
                ('assignment_of_benefits', models.BooleanField(default=True)),
                ('release_of_information', models.BooleanField(default=True)),
                ('prior_authorization_number', models.CharField(blank=True, max_length=100)),
                ('other_payer_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['claim', 'payer_sequence'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.CharField(blank=True, max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('policy_type', models.CharField(choices=[('medicare', 'Medicare'), ('medicaid', 'Medicaid'), ('commercial', 'Commercial'), ('tricare', 'TRICARE'), ('other', 'Other')], default='medicare', max_length=50)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'insurance policies',
                'ordering': ['insured_party', 'payer', 'member_id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='claim',
            name='claims_clai_payer_i_61c515_idx',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='insured_party',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='insuredparty',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='insuredparty',
            name='insured_id_number',
        ),
        migrations.RemoveField(
            model_name='insuredparty',
            name='relationship_to_patient',
        ),
        migrations.AddField(
            model_name='claimcoverage',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='claims.claim'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='insured_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='claims.insuredparty'),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='claims.payer'),
        ),
        migrations.AddField(
            model_name='claimcoverage',
            name='insurance_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_coverages', to='claims.insurancepolicy'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['insured_party'], name='claims_insu_insured_09e005_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['member_id'], name='claims_insu_member__750422_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['policy_type'], name='claims_insu_policy__0af12f_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancepolicy',
            index=models.Index(fields=['is_active'], name='claims_insu_is_acti_560094_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('member_id', ''), _negated=True), models.Q(('group_number', ''), _negated=True), _connector='OR'), fields=('insured_party', 'payer', 'member_id', 'group_number'), name='unique_policy_when_member_or_group_present'),
        ),
        migrations.AddIndex(
            model_name='claimcoverage',
            index=models.Index(fields=['claim'], name='claims_clai_claim_i_7eb436_idx'),
        ),
        migrations.AddIndex(
            model_name='claimcoverage',
            index=models.Index(fields=['insurance_policy'], name='claims_clai_insuran_339a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='claimcoverage',
            index=models.Index(fields=['payer_sequence'], name='claims_clai_payer_s_f2bc6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='claimcoverage',
            constraint=models.UniqueConstraint(fields=('claim', 'payer_sequence'), name='unique_claim_payer_sequence'),
        ),
        migrations.AddConstraint(
            model_name='claimcoverage',
            constraint=models.UniqueConstraint(fields=('claim', 'insurance_policy'), name='unique_claim_insurance_policy'),
        ),
    ]
