# Generated by Django 5.2.16 on 2026-08-14 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimcoverage_insurancepolicy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10Code',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NpiReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('npi', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization')], max_length=20)),
                ('provider_name', models.CharField(max_length=255)),
                ('primary_taxonomy_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('enumeration_date', models.DateField(blank=True, null=True)),
                ('source_last_updated_date', models.DateField(blank=True, null=True)),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['provider_name', 'npi'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_system', models.CharField(choices=[('cpt', 'CPT / HCPCS Level I'), ('hcpcs_level_ii', 'HCPCS Level II')], max_length=30)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField(blank=True)),
                ('effective_start_date', models.DateField(blank=True, null=True)),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code_system', 'code'],
            },
        ),
        migrations.AddField(
            model_name='serviceline',
            name='rendering_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rendered_service_lines', to='claims.provider'),
        ),
        migrations.AddField(
            model_name='claimdiagnosis',
            name='icd10_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_diagnoses', to='claims.icd10code'),
        ),
        migrations.AddField(
            model_name='provider',
            name='npi_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_records', to='claims.npireference'),
        ),
        migrations.AddField(
            model_name='serviceline',
            name='procedure_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_lines', to='claims.procedurecode'),
        ),
        migrations.CreateModel(
            name='ReferenceDataUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset_name', models.CharField(choices=[('nppes', 'NPPES / NPI'), ('icd10_cm', 'ICD-10-CM'), ('procedure_codes', 'CPT / HCPCS')], max_length=50)),
                ('source_name', models.CharField(max_length=255)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('records_loaded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-completed_at', '-created_at'],
                'indexes': [models.Index(fields=['dataset_name', 'status'], name='claims_refe_dataset_f0f86e_idx'), models.Index(fields=['completed_at'], name='claims_refe_complet_9ece24_idx')],
            },
        ),
        migrations.AddField(
            model_name='procedurecode',
            name='source_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_records', to='claims.referencedataupdate'),
        ),
        migrations.AddField(
            model_name='npireference',
            name='source_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npi_records', to='claims.referencedataupdate'),
        ),
        migrations.AddField(
            model_name='icd10code',
            name='source_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icd10_records', to='claims.referencedataupdate'),
        ),
        migrations.AddIndex(
            model_name='procedurecode',
            index=models.Index(fields=['code_system', 'is_active'], name='claims_proc_code_sy_c0ad97_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurecode',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='claims_proc_effecti_f5a78f_idx'),
        ),
        migrations.AddIndex(
            model_name='npireference',
            index=models.Index(fields=['provider_name'], name='claims_npir_provide_82207f_idx'),
        ),
        migrations.AddIndex(
            model_name='npireference',
            index=models.Index(fields=['primary_taxonomy_code'], name='claims_npir_primary_a122df_idx'),
        ),
        migrations.AddIndex(
            model_name='npireference',
            index=models.Index(fields=['is_active'], name='claims_npir_is_acti_7e947d_idx'),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=models.Index(fields=['is_active'], name='claims_icd1_is_acti_75d326_idx'),
        ),
        migrations.AddIndex(
            model_name='icd10code',
            index=models.Index(fields=['effective_start_date', 'effective_end_date'], name='claims_icd1_effecti_a3eabd_idx'),
        ),
    ]
