# Generated by Django 5.2.16 on 2026-08-28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_icd10code_npireference_procedurecode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payer",
            name="address_line_1",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payer",
            name="address_line_2",
            field=models.CharField(default="", max_length=255, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payer",
            name="city",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payer",
            name="state",
            field=models.CharField(
                default="",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="State must be a two-letter code.",
                        regex="^[A-Za-z]{2}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payer",
            name="zip_code",
            field=models.CharField(
                default="",
                max_length=5,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Payer ZIP code must contain exactly 5 digits.",
                        regex="^[0-9]{5}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payer",
            name="zip_code_extension",
            field=models.CharField(
                default="",
                max_length=4,
                blank=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Payer ZIP+4 extension must contain exactly 4 digits.",
                        regex="^[0-9]{4}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
