# Generated by Django 5.2.17 on 2026-09-07 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPartner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('isa_sender_qualifier', models.CharField(default='ZZ', max_length=2, validators=[django.core.validators.RegexValidator(message='Interchange ID qualifier must be two characters.', regex='^[A-Za-z0-9]{2}$')])),
                ('isa_sender_id', models.CharField(max_length=15)),
                ('isa_receiver_qualifier', models.CharField(default='ZZ', max_length=2, validators=[django.core.validators.RegexValidator(message='Interchange ID qualifier must be two characters.', regex='^[A-Za-z0-9]{2}$')])),
                ('isa_receiver_id', models.CharField(max_length=15)),
                ('usage_indicator', models.CharField(choices=[('T', 'Test'), ('P', 'Production')], default='T', max_length=1)),
                ('gs_sender_code', models.CharField(max_length=15)),
                ('gs_receiver_code', models.CharField(max_length=15)),
                ('submitter_name', models.CharField(max_length=60)),
                ('submitter_id', models.CharField(max_length=80)),
                ('submitter_contact_name', models.CharField(max_length=60)),
                ('submitter_contact_phone', models.CharField(blank=True, max_length=20)),
                ('receiver_name', models.CharField(max_length=60)),
                ('receiver_id', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('isa_control_number', models.CharField(max_length=9)),
                ('gs_control_number', models.CharField(max_length=9)),
                ('st_control_number', models.CharField(max_length=9)),
                ('claim_count', models.PositiveIntegerField(default=0)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('total_charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('trading_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='edi.tradingpartner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_id', models.UUIDField()),
                ('claim_number', models.CharField(max_length=60)),
                ('position', models.PositiveIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='edi.submissionbatch')),
            ],
            options={
                'ordering': ['batch', 'position'],
                'indexes': [models.Index(fields=['claim_id'], name='edi_batchcl_claim_i_72870e_idx')],
                'unique_together': {('batch', 'claim_id')},
            },
        ),
        migrations.CreateModel(
            name='ControlNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('interchange', 'Interchange, ISA13'), ('group', 'Functional group, GS06'), ('transaction', 'Transaction set, ST02')], max_length=20)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('trading_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_numbers', to='edi.tradingpartner')),
            ],
            options={
                'ordering': ['trading_partner', 'level'],
                'unique_together': {('trading_partner', 'level')},
            },
        ),
    ]
